### ISSUE TITLE
Quick Sort Programs needed in every possible language :)

### ISSUE THREAD

**Issue by kohchihao** [kohchihao/quick-sort#1]
Feel free to add any Quick Sort programs! Remember to refer to this ~

**Comment by bamsarts** [comment]
Hello, could I help with this?

**Comment by bamsarts** [comment]
i will take 

Happy Hacktoberfest

**Comment by kohchihao** [comment]
@bamsarts yup. thanks!

**Comment by haggcoder** [comment]
I would like to add a **Java** Implementation of Quick Sort.

**Comment by mahasak** [comment]
Sound interesting, i am already sent Python version already. Do you think we should separate the label ? as Github magic will close issue when we merged.

**Comment by kohchihao** [comment]
@mahasak just merged. doesnt seem like it will close issue :)

**Comment by yasirunilan** [comment]
Shall I add c++ implementation

**Comment by shiri1248** [comment]
I would like add  implementation in c

**Comment by shiri1248** [comment]
#4

**Comment by shiri1248** [comment]
#4

**Comment by shiri1248** [comment]
@kohchihao  is there any conflict while merging

**Comment by cmd-tea** [comment]
I would like to add implementation of C#!

**Comment by shiri1248** [comment]
#4

**Comment by rishz** [comment]
Hey! Added the **JavaScript** implementation of Quick Sort.

**Comment by cmd-tea** [comment]
c# implementation: https://github.com/kohchihao/quick-sort/pull/11

**Comment by bamsarts** [comment]
golang language added #12

**Comment by drevantonder** [comment]
Do we need a c++ version or does the c version work for both?

**Comment by Programm3r** [comment]
Hey, is only quick sort algorithms allowed? Thanks!

**Comment by kohchihao** [comment]
@Programm3r yeah only quick sort haha :)

**Comment by Programm3r** [comment]
@kohchihao oki doki thanks

**Comment by jerold** [comment]
Another Dart implementation https://github.com/kohchihao/quick-sort/pull/26

**Comment by cupOJoseph** [comment]
@kohchihao is this issue still open?
